apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    release: '${parameters.release}'
  name: 'nginx-deployment-${parameters.release}'
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: nginx
      release: '${parameters.release}'
  template:
    metadata:
      labels:
        app: nginx
        release: '${parameters.release}'
    spec:
      containers:
        - image: 'quay.io/opsmxpublic/simple-webapp'
          name: simple-webapp
          env:
          - name: APP_COLOR
            value: blue
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: '${parameters.service_name}'
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx
    release: '${parameters.release}'
