

commonLabels:
  app: hello

resources:
- https://github.com/kubernetes-sigs/kustomize//examples/multibases?timeout=120&ref=v3.3.1
- deployment.yaml
- service.yaml
- configMap.yaml

namePrefix: remote-
